// <auto-generated />
using System;
using Apes.SugarKingdom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apes.SugarKingdom.Data.Migrations
{
    [DbContext(typeof(SugarContext))]
    [Migration("20240221132654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Apes.SugarKingdom.Data.VersusPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("ModifiedDate");

                    b.Property<int>("Points")
                        .HasColumnType("int(11)")
                        .HasColumnName("Points");

                    b.Property<string>("Wallet")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Wallet");

                    b.HasKey("Id");

                    b.ToTable("VersusPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
