name: Build and deploy .NET Core application to Web App sugar-app-service with API Management Service sugar-apim-sugar-api
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: sugar-app-service
  AZURE_WEBAPP_PACKAGE_PATH: Apes.SugarKingdom.Api/publish
  AZURE_APIM_RESOURCE_PATH: /api/versus
  AZURE_APIM_RESOURCEGROUP: sugar-api
  AZURE_APIM_SERVICENAME: sugar-apim
  AZURE_APIM_API_ID: sugar-api
  AZURE_APIM_APPSERVICEURL: https://sugar-app-service.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: Apes.SugarKingdom.Api/publish/swagger.json
  API_IMPORT_DLL: Apes.SugarKingdom.Api/bin/Release/net8.0/Apes.SugarKingdom.Api.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: Apes.SugarKingdom.Api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup SwashBuckle .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}
    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build
    - name: Publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.sugar_app_service_9585 }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.sugar_apim_SPN }}
    - name: logout
      run: >
        az logout
